spring:
  kafka:
    bootstrap-servers: localhost:9092
    # kafka的主题配置
    topic: todoItemTopic
    consumer:
      group-id: todoItemGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      # 批量消费记录数
      max-poll-records: 5

    listener:
      missing-topics-fatal: false

    producer:
      retries: 0
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

  # 二维码图片定时任务扫描目录/kafka消费消息之后，生成的二维码图片存放路径
  qrCodeDir: /u01/qrCode/consumer/
  # 二维码图片备份目录
  qrCodeBackupDir: /u01/qrCode/backup/
  # 打印机名称
  printerName: Microsoft Print to PDF